// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using construcaoAPI_INF12.Data;

#nullable disable

namespace construcaoAPI_INF12.Api.Migrations
{
    [DbContext(typeof(LojaClientesDbContext))]
    [Migration("20241204173230_Criacao01")]
    partial class Criacao01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("construcaoAPI_INF12.Api.Modelos.Produto", b =>
                {
                    b.Property<int>("idProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idProduto"));

                    b.Property<DateTime>("dataProduto")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("descricaoProduto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("estoqueProduto")
                        .HasColumnType("int");

                    b.Property<string>("nomeProduto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("precoProduto")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("idProduto");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("construcaoAPI_INF12.Modelos.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("construcaoAPI_INF12.Modelos.ItensPedido", b =>
                {
                    b.Property<int>("idItemPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("idItemPedido"));

                    b.Property<int>("idPedido")
                        .HasColumnType("int");

                    b.Property<int>("idProduto")
                        .HasColumnType("int");

                    b.Property<float>("precoUnitarioItemPedido")
                        .HasColumnType("float");

                    b.Property<int>("quantidadeItemPedido")
                        .HasColumnType("int");

                    b.HasKey("idItemPedido");

                    b.HasIndex("idPedido");

                    b.HasIndex("idProduto");

                    b.ToTable("ItensPedidos");
                });

            modelBuilder.Entity("construcaoAPI_INF12.Modelos.Pedido", b =>
                {
                    b.Property<int>("idPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("dataPedido")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("idCliente")
                        .HasColumnType("int");

                    b.Property<string>("observacoesPedido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("statusPedido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("valorTotalPedido")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("idPedido");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("construcaoAPI_INF12.Modelos.ItensPedido", b =>
                {
                    b.HasOne("construcaoAPI_INF12.Modelos.Pedido", "Pedido")
                        .WithMany("itensPedidos")
                        .HasForeignKey("idPedido")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("construcaoAPI_INF12.Api.Modelos.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("idProduto")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("construcaoAPI_INF12.Modelos.Pedido", b =>
                {
                    b.HasOne("construcaoAPI_INF12.Modelos.Cliente", null)
                        .WithMany("Pedidos")
                        .HasForeignKey("idPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("construcaoAPI_INF12.Modelos.Cliente", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("construcaoAPI_INF12.Modelos.Pedido", b =>
                {
                    b.Navigation("itensPedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
